sudo: required
dist: bionic
language: csharp
solution: Etdb.UserService.AspNetCore.sln
mono: none
dotnet: 5.0.100-preview.6.20318.15
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$CLEANCODELABS_NUGET_KEY" "$TRAVIS_TAG"