dist: bionic
language: csharp
solution: entityframeworkcore-genericrepository
mono: none
dotnet: 2.2.105
stages:
  - build
  - test
  - publish
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$CLEANCODELABS_NUGET_KEY" "$TRAVIS_TAG"

